name = "DelaySSAToolkit"
uuid = "d39380a9-d0d7-4ae6-ae63-0e8d8b7efa9e"
authors = ["Xiaoming Fu"]
version = "0.2.1"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqJump = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ArrayInterface = "2.8, 3.0, 4, 5"
DataStructures = "0.18"
DiffEqBase = "6.54.0"
DiffEqJump = "7.0, 8.0"
DocStringExtensions = "0.8"
FunctionWrappers = "1.0"
ModelingToolkit = "6.3, 7.0, 8.0"
RandomNumbers = "1.3"
Reexport = "0.2, 1.0"
StaticArrays = "0.10, 0.11, 0.12, 1.0"
UnPack = "1.0.2"
julia = "1.6, 1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
